auto: true
markdown: rdiscount
permalink: /blog/:title
name: Knight-Mozilla OpenNews
description: The blog for the Knight-Mozilla OpenNews project
url: http://www.opennews.org/blog
rdiscount:
  extensions: [smart]
